### ISSUE TITLE
需在 handle 函数签名中指定 Bot 为 OneBot V11 的 Bot

### ISSUE THREAD

**Issue by j1g5awi** [H-xiaoH/nonebot-plugin-apex-api-query#12]
我发现您在 handle 函数签名中并未指定 Bot 为 OneBot V11 的 Bot，却在部分 handle 里使用了 OneBot V11 的 MessageSegment，这会导致其他适配器的事件仍会被本插件的 matcher 所捕获。但由于您使用的是 OneBot V11 的 MessageSegment，消息可能无法发出并报错，同时阻断之后的事件处理流程。

**Comment by H-xiaoH** [comment]
https://github.com/H-xiaoH/nonebot-plugin-apex-api-query/commit/e52f037f1fa9a1d4e5e31969dc9239a8887be019

已对其问题进行修改。还有其他的逻辑问题吗？

**Comment by j1g5awi** [comment]
Fine.
