### ISSUE TITLE
在频道中不返回消息

### ISSUE THREAD

**Issue by Dr-WeiAL** [H-xiaoH/nonebot-plugin-apex-api-query#14]
在群里使用是正常的，但是在频道中使用虽然控制台有反应，但不会发送对应消息
```
03-10 22:56:57 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_apex_api_query)
03-10 22:56:57 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_apex_api_query) running complete
```

**Comment by H-xiaoH** [comment]
因为还没做频道适配，我的 Bot 账号没有使用频道功能的权限，所以这个适配需要搁置一段时间。

**Comment by Dr-WeiAL** [comment]
> 因为还没做频道适配，我的 Bot 账号没有使用频道功能的权限，所以这个适配需要搁置一段时间。

好吧，不过以前都还能在频道使用，不知道什么时候更新后就不能用了

**Comment by H-xiaoH** [comment]
> > 因为还没做频道适配，我的 Bot 账号没有使用频道功能的权限，所以这个适配需要搁置一段时间。
> 
> 好吧，不过以前都还能在频道使用，不知道什么时候更新后就不能用了

那你可以尝试退回旧的版本，新版本为了别的插件的兼容性修改。

**Comment by H-xiaoH** [comment]
已更新 [23.3.16](https://pypi.org/project/nonebot-plugin-apex-api-query/23.3.16/) 适配频道。
