### ISSUE TITLE
限时地图名未翻译

### ISSUE THREAD

**Issue by Dr-WeiAL** [H-xiaoH/nonebot-plugin-apex-api-query#15]
![aeccfd1345247d46cee24ad8df9cb09e](https://user-images.githubusercontent.com/47446553/225616189-953b039d-2cc0-4f67-a1a8-acc0c19f6387.jpg)

**Comment by H-xiaoH** [comment]
https://github.com/H-xiaoH/nonebot-plugin-apex-api-query/commit/00db21a6b3660d8cb233235ee261f77acf95189c
