### ISSUE TITLE
刚配置这个插件，不好意思对于我来说理解不是很到位

### ISSUE THREAD

**Issue by DragonSauce** [H-xiaoH/nonebot-plugin-apex-api-query#16]
![图片](https://user-images.githubusercontent.com/42651551/226192536-e23de947-bf2d-4513-b389-3902cc203384.png)

这里是否可以改成可复制粘贴的或者是直接像

**Comment by DragonSauce** [comment]
![图片](https://user-images.githubusercontent.com/42651551/226192604-53e141eb-0eee-4119-9cd9-d7a031454a02.png)

**Comment by DragonSauce** [comment]
如果是按照上面表示的话 
这样子更好理解配置呢，表格摆在这里我也不知道APEX_API_KEY 后面需不需要空格 等号 双引号什么的
就很苦恼 我这边提示我 cannot open resource

**Comment by H-xiaoH** [comment]
https://v2.nonebot.dev/docs/tutorial/configuration

NoneBot 2 文档中有详细的配置说明，您可以参考其示例来编写您的配置文件。

如果你在使用过程中出现了错误，请以 MarkDown 或截图的形式发送 Log，这能很好的给开发者提供详细信息以分析问题。

**Comment by YCJ-GuLi** [comment]
> 
你的问题解决了吗？ 我也遇到了跟你一样的问题

**Comment by H-xiaoH** [comment]
> > 
> 
> 你的问题解决了吗？ 我也遇到了跟你一样的问题

如果你在使用过程中出现了错误，请以 MarkDown 或截图的形式发送 Log，这能很好的给开发者提供详细信息以分析问题。

**Comment by YCJ-GuLi** [comment]
> 

抱歉 不是插件的问题 是我的问题 第一次使用nonebot框架搭建机器人 api密钥填写的格式不是很清楚  文档中的配置信息看的我眼花缭乱

**Comment by H-xiaoH** [comment]
> > 
> 
> 抱歉 不是插件的问题 是我的问题 第一次使用nonebot框架搭建机器人 api密钥填写的格式不是很清楚 文档中的配置信息看的我眼花缭乱

https://v2.nonebot.dev/docs/tutorial/configuration#env-%E6%96%87%E4%BB%B6

NoneBot 2 官方文档中提供了详细的配置方法。可参考其中的示例。

**Comment by DragonSauce** [comment]
我安装此模块了，机器人也有响应命令，输入ID以后后台显示cannot open resource 已填入Apex获取的api

**Comment by DragonSauce** [comment]
![图片](https://user-images.githubusercontent.com/42651551/227210020-c78e357f-617c-4344-a12a-512b5c11757c.png)
不知道这样是否正确 ，但给id以后返回值是 cannot open resource然后机器人就没有回应

**Comment by H-xiaoH** [comment]
> ![图片](https://user-images.githubusercontent.com/42651551/227210020-c78e357f-617c-4344-a12a-512b5c11757c.png)
> 不知道这样是否正确 ，但给id以后返回值是 cannot open resource然后机器人就没有回应

配置没有问题。

如果你在使用过程中出现了错误，请以 MarkDown 或截图的形式发送 Log，这能很好的给开发者提供详细信息以分析问题。

**Comment by H-xiaoH** [comment]
> 如果是按照上面表示的话 这样子更好理解配置呢，表格摆在这里我也不知道APEX_API_KEY 后面需不需要空格 等号 双引号什么的 就很苦恼 我这边提示我 cannot open resource

https://github.com/H-xiaoH/nonebot-plugin-apex-api-query/issues/7

**Comment by H-xiaoH** [comment]
> ![图片](https://user-images.githubusercontent.com/42651551/227210020-c78e357f-617c-4344-a12a-512b5c11757c.png) 不知道这样是否正确 ，但给id以后返回值是 cannot open resource然后机器人就没有回应

https://github.com/H-xiaoH/nonebot-plugin-apex-api-query/issues/7
