### ISSUE TITLE
调用报错

### ISSUE THREAD

**Issue by zhaoZiQu** [H-xiaoH/nonebot-plugin-apex-api-query#18]
![image](https://user-images.githubusercontent.com/65691999/228454187-98e93cea-ae73-4969-af0d-52b5ee7924e3.png)
![image](https://user-images.githubusercontent.com/65691999/228454236-a512f3e2-ebe8-4663-bdb1-84f95b6b431e.png)
![image](https://user-images.githubusercontent.com/65691999/228454399-93aa79bf-7a12-4016-9956-31a82601fa8c.png)
qq后续无结果，后台报错

**Comment by zhaoZiQu** [comment]
![image](https://user-images.githubusercontent.com/65691999/228454585-cb83db66-29af-4689-90d6-8aaa200eae09.png)
这样算是申请成功了吧

**Comment by H-xiaoH** [comment]
/绑定 [玩家 UID]

玩家 UID 可以在 /玩家 [玩家名称] 中获取。

**Comment by H-xiaoH** [comment]
> ![image](https://user-images.githubusercontent.com/65691999/228454187-98e93cea-ae73-4969-af0d-52b5ee7924e3.png) ![image](https://user-images.githubusercontent.com/65691999/228454236-a512f3e2-ebe8-4663-bdb1-84f95b6b431e.png) ![image](https://user-images.githubusercontent.com/65691999/228454399-93aa79bf-7a12-4016-9956-31a82601fa8c.png) qq后续无结果，后台报错

https://github.com/H-xiaoH/nonebot-plugin-apex-api-query/issues/7

**Comment by zhaoZiQu** [comment]
多谢，解决了
