### ISSUE TITLE
api问题

### ISSUE THREAD

**Issue by Xiao-yux** [H-xiaoH/nonebot-plugin-apex-api-query#2]
![image](https://user-images.githubusercontent.com/79674967/202656029-3f984791-6f9e-4386-bb5a-92c61ea240b0.png)
api我配置了啊
![image](https://user-images.githubusercontent.com/79674967/202656098-56b80fd9-5a6a-4507-b982-6df0dd8a99c1.png)
![image](https://user-images.githubusercontent.com/79674967/202656194-032a2f17-dbc0-40c5-8392-867e3435d078.png)

**Comment by H-xiaoH** [comment]
先手动测试一下 API 是否正常："https://api.mozambiquehe.re/maprotation?auth=YOUR_API_KEY"。
其次确保文件正确保存并被 nb2 重新载入并读取。
如果可以，请反馈一下版本号。

**Comment by Xiao-yux** [comment]
![image](https://user-images.githubusercontent.com/79674967/203935811-367535b0-7a96-44fd-a9a0-b49c882fc445.png)
可以

**Comment by Xiao-yux** [comment]
![image](https://user-images.githubusercontent.com/79674967/203935964-18917cee-44f0-4ab1-a612-f5f51b5596fd.png)

**Comment by Xiao-yux** [comment]
![image](https://user-images.githubusercontent.com/79674967/203936109-5f242d06-7dbe-429d-b3bb-74c1976a7807.png)
今天查询还是这样

**Comment by Xiao-yux** [comment]
版本 ：我7天前才下载这个插件开始使用

**Comment by H-xiaoH** [comment]
> ![image](https://user-images.githubusercontent.com/79674967/203935811-367535b0-7a96-44fd-a9a0-b49c882fc445.png) 可以

这不是正确的 API KEY 可用性测试方法。请再试。
详细的测试方法您可以在 [此处](https://apexlegendsapi.com/) 获得。

**Comment by H-xiaoH** [comment]
如果可以请更新至 22.11.30 版本，并根据 [README](https://github.com/H-xiaoH/nonebot-plugin-apex-api-query#readme) 配置后尝试使用。
