### ISSUE TITLE
在查询eaid个人信息的时候提示我查询失败

### ISSUE THREAD

**Issue by WasTed77** [H-xiaoH/nonebot-plugin-apex-api-query#20]
在查询eaid个人信息的时候提示我查询失败: API 错误: {"Error": "Your request has been declined because of server load issue, Origin refusing the connection or a wrong username."}或者是查询失败: API 错误: {"Error": "Player exists but has never played Apex Legends"}是什么原因呀​
控制台无报错

还有赛季制造武器没有更新

**Comment by H-xiaoH** [comment]
> 在查询eaid个人信息的时候提示我查询失败: API 错误: {"Error": "Your request has been declined because of server load issue, Origin refusing the connection or a wrong username."}或者是查询失败: API 错误: {"Error": "Player exists but has never played Apex Legends"}是什么原因呀​ 控制台无报错

第一个错误是查询服务器满载了，稍后重试。
第二个错误是你的 ID 不存在。使用您的 EAID 来查询。

> 还有赛季制造武器没有更新

本插件只作 数据获取 和 内容转换，所有的数据都来源自 API，所以不能确保内容的正确性。
