### ISSUE TITLE
查询内容优化

### ISSUE THREAD

**Issue by veadex** [H-xiaoH/nonebot-plugin-apex-api-query#22]
大佬有考虑过优化一下查询内容吗？例如这样，删掉了一些重复内容，加上击杀器，猎杀查询的话加上一个赛季结束时间。
![Cache_-1d6540ca82382dec.jpg](https://github.com/H-xiaoH/nonebot-plugin-apex-api-query/assets/65024689/3a0e1b4d-0c57-4cae-93fb-13a50ababd88)

![Cache_66d707d9f518fdbc.jpg](https://github.com/H-xiaoH/nonebot-plugin-apex-api-query/assets/65024689/7990b27c-0e8b-403e-82d0-ec1c23d6ac51)

**Comment by veadex** [comment]
进一步优化的就是调用翻译的api，然后把击杀器信息翻译一下

**Comment by H-xiaoH** [comment]
感谢您的反馈，我会将下一次更新中加入此项目。现此 Issue 将保留。

**Comment by veadex** [comment]
我看了看Apex的api，没有找到有关赛季结束的时间信息，我是爬的一个网站的信息，然后转换格式后写上去的。
今天更新了一下这个插件，把我原来写的内容更新掉了，我还没有留备份，不能提供我写的内容了😂😂

**Comment by H-xiaoH** [comment]
> 我看了看Apex的api，没有找到有关赛季结束的时间信息，我是爬的一个网站的信息，然后转换格式后写上去的。 今天更新了一下这个插件，把我原来写的内容更新掉了，我还没有留备份，不能提供我写的内容了😂😂

“一个网站” 的信息能提供一下嘛？

**Comment by veadex** [comment]
> > 我看了看Apex的api，没有找到有关赛季结束的时间信息，我是爬的一个网站的信息，然后转换格式后写上去的。 今天更新了一下这个插件，把我原来写的内容更新掉了，我还没有留备份，不能提供我写的内容了😂😂
> 
> “一个网站” 的信息能提供一下嘛？

还有一些内容，你可以看一下，我获取的时区是太平洋时间，所以转换了一下时区，
```
import requests
from bs4 import BeautifulSoup
from datetime import datetime, timezone, timedelta
import re

url = "https://apex.tracker.gg/"
response = requests.get(url)
html = response.text

soup = BeautifulSoup(html, "html.parser")

title_element = soup.select_one('span[title]')
if title_element:
    title = title_element.get('title')
    
    # 剔除时区偏移部分
    pattern = r'\(.*\)'
    title = re.sub(pattern, '', title).strip()
    
    # 解析时间字符串为datetime对象
    dt = datetime.strptime(title, "%a %b %d %Y %H:%M:%S GMT%z")

    # 转换为中国标准时间
    target_tz = timezone(timedelta(hours=8))
    dt = dt.astimezone(target_tz)

    # 格式化为特定的时间字符串
    formatted_time = dt.strftime("%Y-%m-%d %H:%M:%S")
    print(formatted_time)
else:
    print("找不到标题元素")
```
