### ISSUE TITLE
关于api申请的问题

### ISSUE THREAD

**Issue by Nana7mij** [H-xiaoH/nonebot-plugin-apex-api-query#3]
我在申请api过程中发现
Project description 一栏中如果填写中文的话申请的api key是无法使用的
在Dashboard界面会报404 Error，且直接返回Error: API key doesn't exist !
而且该api key无法再次登录会显示Sorry, no matching API key was found. Please try again.

**Comment by H-xiaoH** [comment]
如果您的 API 存在问题，可以到官方 [Discord](https://discord.gg/qd9cZQm) 社区(英语)获取帮助。
