### ISSUE TITLE
功能建议：自动查询地图轮换

### ISSUE THREAD

**Issue by Dr-WeiAL** [H-xiaoH/nonebot-plugin-apex-api-query#4]
在第一次查询后记录地图轮换剩余时间，在轮换后自动查询发送到指定群/频道

**Comment by H-xiaoH** [comment]
感谢您的关注，确实是个不错的功能建议，我会将此加入计划中。

**Comment by H-xiaoH** [comment]
https://github.com/H-xiaoH/nonebot-plugin-apex-api-query/commit/5c43cbbab7af934e2ba4ebc105fadb430b7645b0
