### ISSUE TITLE
功能建议：绑定玩家信息

### ISSUE THREAD

**Issue by Dr-WeiAL** [H-xiaoH/nonebot-plugin-apex-api-query#5]
添加一个绑定UID/ID的命令，绑定后群员发送查询玩家信息命令但不输入任何额外信息时，默认查询群员所绑定的账号

**Comment by H-xiaoH** [comment]
感谢您的关注，确实是个不错的功能建议，我会将此加入计划中。

**Comment by H-xiaoH** [comment]
https://github.com/H-xiaoH/nonebot-plugin-apex-api-query/commit/e5bb728bac6ea0083db0e0ba402a13173cd0cbf5
