### ISSUE TITLE
Failed to import "nonebot_plugin_apex_api_query"

### ISSUE THREAD

**Issue by purelolly** [H-xiaoH/nonebot-plugin-apex-api-query#6]
![L7%08 @74~}K$BX Z6EJX54](https://user-images.githubusercontent.com/78009999/209433622-0458a706-7cb6-44bd-8297-2fd7abe43133.png)
![B7CV~35{AV)@S6)JY@8PLCE](https://user-images.githubusercontent.com/78009999/209433629-bee2a94d-7a89-49ea-baee-62e5aed4e1c0.png)

**Comment by H-xiaoH** [comment]
您的 nonebot_plugin_apscheduler 插件需要更新。
您可以在 nb 运行目录中运行 `nb plugin install nonebot-plugin-apscheduler` 进行更新，
或在 [nonebot-plugin-apscheduler](https://github.com/nonebot/plugin-apscheduler) 中手动更新此插件。

**Comment by purelolly** [comment]
![{G}_U3J E8} 7U6H8I9~9_F](https://user-images.githubusercontent.com/78009999/209469549-80c4c185-3a82-4238-9353-38b00e354f10.png)

**Comment by H-xiaoH** [comment]
我看不懂。

**Comment by purelolly** [comment]
> 我看不懂。

查询失败: API 错误: Error: API key doesn't exist !

**Comment by purelolly** [comment]
> 我看不懂。

申请了api，但任然无效

**Comment by H-xiaoH** [comment]
参考以下问题。
https://github.com/H-xiaoH/nonebot-plugin-apex-api-query/issues/2
https://github.com/H-xiaoH/nonebot-plugin-apex-api-query/issues/3

**Comment by purelolly** [comment]
> 

![UFW54)%6PIDF7 W7TF0`HVI](https://user-images.githubusercontent.com/78009999/209777070-24278239-bf77-4b78-bb59-92986a3ead93.png)

**Comment by H-xiaoH** [comment]
https://github.com/H-xiaoH/nonebot-plugin-apex-api-query/issues/2#issuecomment-1331456933

**Comment by H-xiaoH** [comment]
尝试在 https://portal.apexlegendsapi.com/ 中登录您的 API.

**Comment by purelolly** [comment]
> 尝试在 https://portal.apexlegendsapi.com/ 中登录您的 API.

我已得到解决，申请api，用途不能写中文，要用英文，用中文生成出的key是错误的
建议作者在文档里面说明一下，让那些遇到和我相同的问题，可以得到解决
