### ISSUE TITLE
错误反馈：赛季制造仍然是上半赛季的

### ISSUE THREAD

**Issue by Dr-WeiAL** [H-xiaoH/nonebot-plugin-apex-api-query#8]
![@QLHK15}MHE)H8W~WMACT_M](https://user-images.githubusercontent.com/47446553/215428972-af4ed31a-8cca-4365-afa3-48415a7de2fc.PNG)

**Comment by H-xiaoH** [comment]
数据由 API 提供，本插件仅作数据获取和内容转换。故此问题无法修复。
