### ISSUE TITLE
错误反馈：订阅失败

### ISSUE THREAD

**Issue by Darling0202** [H-xiaoH/nonebot-plugin-apex-api-query#9]
订阅地图轮换失败: The following arguments have not been supplied: api_t2i
订阅制造轮换失败: The following arguments have not been supplied: api_t2i
其他功能都可以正常运行，后台也没有报错

**Comment by H-xiaoH** [comment]
https://github.com/H-xiaoH/nonebot-plugin-apex-api-query/commit/702a645ae58ec105ca14cb83689c4b2e8d3063a4
已修复并推送至 Pypi，如使用镜像源请等待镜像源刷新后更新插件。感谢您的使用。
